[package]
name = "hornystein"
version = "0.1.0"
edition = "2021"

[dependencies]
image = { version = "0.25.2", features = ["gif"] }
minifb = "0.27.0"
mouse-rs = "0.4.2"
nalgebra-glm = "0.19.0"
rand = "0.8.5"
rodio = "0.19.0"
